version: '3.9'

services:
  web:
    build:
      context: ../myweb  # Set the correct build context
    ports:
      - "80:8000"
    volumes:
      - "../myweb:/app"  # Ensure the correct path
    environment:
      - DEBUG=True
